### ISSUE TITLE
Creating a new contact 

### ISSUE THREAD

**Issue by brunocantisano** [ethnchao/docker-nagios#1]
After creating a contact, the file appears inside the directory but is not inserted in the database, showing an error message . If I changed the admin email, the value is changed correctly.

**Comment by ethnchao** [comment]
Thank you for the reply, I've busy for the business thing recently, sorry for not replying this issue in time.

I just updated the code and I will reply later.

**Comment by brunocantisano** [comment]
Great. Your code helped me a lot to understand containers. Please, warn me
as soon as you update the code

Em Qua, 30 de mai de 2018 08:58, ethnchao <notifications@github.com>
escreveu:

**Comment by ethnchao** [comment]
@brunocantisano Now try to pull the new image by following command:
docker pull ethnchao/nagios
or
docker pull ethnchao/nagios:4.3.4-alpha

**Comment by brunocantisano** [comment]
Hi,

Just to inform.

I really enjoyed the container, but I read that is not good to create
containers that runs as root.

reference:
https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b


Thanks again for your help.



2018-05-31 4:28 GMT-03:00 ethnchao <notifications@github.com>:
