### ISSUE TITLE
how to use grafana

### ISSUE THREAD

**Issue by michabbb** [ethnchao/docker-nagios#10]
hi,

can someone please tell me, how i can use grafana with this build ?
i see that´s enabled, I can call the dashboard, but there is nothing configured and I don´t know what needs to be changed.
is grafana used here to show something that is stored in the MySQL database ??

thanks for any help!

**Comment by ethnchao** [comment]
This git repository is just a hobby at that time when I just learned docker, you can try some other monitor solution, like zabbix, open-falcon, etc.
