### ISSUE TITLE
Nagios Email Notifications not sending emails

### ISSUE THREAD

**Issue by oktavianusrande** [ethnchao/docker-nagios#11]
Log File Navigation

![image](https://user-images.githubusercontent.com/84651917/119247316-f691e600-bbba-11eb-9e62-da5da28adaa8.png)

**Comment by websvcPT** [comment]
Edit the commands "notify-*-by-email" and use the correct path `/usr/bin/mail` the configured one  has /usr duplicated

**Comment by ethnchao** [comment]
This git repository is just a hobby at that time when I just learned docker, you can try some other monitor solution, like zabbix, open-falcon, etc.
