### ISSUE TITLE
Add environment variables for UID/GID when running docker as non-root user

### ISSUE THREAD

**Issue by Chaz6** [ethnchao/docker-nagios#12]
When running docker as a non-root users, docker will still by default create files as uid/gid 0, which means these files cannot be accessed without superuser privilege. Please add a couple of environment variables, e.g. VUID/VGID, so that files created by docker can be created using a different uid/gid.

**Comment by ethnchao** [comment]
This git repository is just a hobby at that time when I just learned docker, you can try some other monitor solution, like zabbix, open-falcon, etc.
