### ISSUE TITLE
livestatus missing

### ISSUE THREAD

**Issue by scobosb** [ethnchao/docker-nagios#13]
Hi, livestatus is missing, where can be downloaded now?

**Comment by ethnchao** [comment]
Hi, I found the version 1.2.8p25 of livestatus, [https://mirrors.xtom.nl/freebsd-ports/distfiles/check_mk/mk-livestatus-1.2.8p25.tar.gz](https://mirrors.xtom.nl/freebsd-ports/distfiles/check_mk/mk-livestatus-1.2.8p25.tar.gz), the 1.2.8p20 cannot be found.

The mk-livestatus is not available in it's official site, looks like they already delete it on the archive page, I can hardly find it.

I haven't paid attention to check-mk related things for a long time, also the Nagios. This git repository is just a hobby at that time when I just learned docker, you can try some other monitor solution, like zabbix, open-falcon, etc.

Life is changing so fast, gook luck.

**Comment by ethnchao** [comment]
[mk-livestatus-1.2.8p25.tar.gz](https://github.com/ethnchao/docker-nagios/files/8729168/mk-livestatus-1.2.8p25.tar.gz)
