### ISSUE TITLE
Container won't start

### ISSUE THREAD

**Issue by simonwibberley** [ethnchao/docker-nagios#2]
Hi there - this looks like an extremely useful image: just what I was looking for. However, I'm getting:

```
 * Starting Grafana Server
   ...done.
Starting nagios: done.
Started runsvdir, PID is 135
Error processing config file '/usr/local/nagios/etc/ndo2db.cfg'.
```
on `start`. Have I missed configuration step?

Many thanks.

**Comment by VitaKiyanova** [comment]
same problem here

**Comment by ethnchao** [comment]
Thank you for the reply, I've busy for the business thing recently, sorry for not replying this issue in time.

I just updated the code and I will reply later.

**Comment by ethnchao** [comment]
Now try pull the new image:

**Comment by ethnchao** [comment]
Now try to pull the new image by following command:
docker pull ethnchao/nagios
or 
docker pull ethnchao/nagios:4.3.4-alpha

**Comment by ethnchao** [comment]
@simonwibberley @VitaKiyanova Update available now.
