### ISSUE TITLE
Sending E-Mail

### ISSUE THREAD

**Issue by vnetmx** [ethnchao/docker-nagios#4]
When I use the option "Send out mail for selected items" to send a manual notification email, this dont work, the api request response 200 but the mail never go out, no error. Just "mail sent!".

Also, ..I was thinking in add ssmtp server (https://wiki.archlinux.org/index.php/SSMTP) to allow use gmail, sendgrid, aws ses, etc... to send email notifications.

**Comment by ethnchao** [comment]
I will just check on this later,thanks for your reply.

**Comment by ethnchao** [comment]
@vnetmx Sorry to reply to you so late, I didn't test the mail function before, today I test it, then I found out that mail is no functional at all.

After many try and retry, bsd-mailx just don't work at all, so I will consider replace it with heirloom-mailx, and upgrade nagios to 4.4.6. 

The new release will coming soon.

**Comment by ethnchao** [comment]
Looks like "Send out mail for selected items" is a feature of adagios. But I can't find any adagios settings about that on the adagio official site. Sorry about that. @vnetmx
